from .Aritmetica import Aritmetica
from .Asignacion import Asignacion
from .Declaracion import Declaracion
from .Identificador import Identificador
from .IncrementoDecremento import IncrementoDecremento
from .Logica import Logica
from .Primitivo import Primitivos
from .Relacional import Relacional
from .Casteo import Casteo
from .DeclaracionArreglos import DeclaracionArregloTipo1,DeclaracionArregloTipo2
from .Arreglo import Arreglo,ObtenerValorArreglo
from .AsignacionArreglos import AsignacionArreglo